import type { Job, Company } from "./types";

export const categories = [
  "Semua Kategori",
  "Engineering",
  "Design",
  "Product",
  "Marketing",
  "Sales",
  "Operations",
  "Finance",
  "HR",
  "Legal",
  "Customer Support",
];

export const jobTypes = [
  "Semua Tipe",
  "Full-time",
  "Part-time",
  "Kontrak",
  "Magang",
  "Remote",
];

export const experienceLevels = [
  "Semua Level",
  "Fresh Graduate",
  "Junior",
  "Mid Level",
  "Senior",
  "Lead",
  "Executive",
];

export const locations = [
  "Semua Lokasi",
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Barat",
  "Jakarta Timur",
  "Jakarta Utara",
  "Bogor",
  "Depok",
  "Tangerang",
  "Tangerang Selatan",
  "Bekasi",
  "Remote",
];

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    companyId: "1",
    company: "Tokopedia",
    companyLogo: "/tokopedia-logo-green.jpg",
    location: "Jakarta Selatan",
    type: "full-time",
    salary: { min: 25000000, max: 45000000, currency: "IDR" },
    description:
      "Bergabunglah dengan tim engineering Tokopedia untuk membangun platform e-commerce terbesar di Indonesia.",
    requirements: [
      "5+ tahun pengalaman React",
      "Mahir TypeScript",
      "Pengalaman dengan modern CSS",
      "Kemampuan komunikasi yang baik",
    ],
    benefits: [
      "Gaji kompetitif",
      "BPJS Kesehatan & Ketenagakerjaan",
      "Cuti tahunan",
      "WFH flexible",
    ],
    category: "Engineering",
    experience: "senior",
    postedAt: "2025-01-25",
    featured: true,
    tags: ["React", "TypeScript", "Next.js", "Tailwind"],
  },
  {
    id: "2",
    companyId: "2",
    title: "Product Designer",
    company: "Gojek",
    companyLogo: "/gojek-logo-green.jpg",
    location: "Jakarta Selatan",
    type: "full-time",
    salary: { min: 18000000, max: 30000000, currency: "IDR" },
    description:
      "Bergabung dengan tim design Gojek untuk menciptakan pengalaman pengguna yang luar biasa untuk jutaan pengguna.",
    requirements: [
      "4+ tahun pengalaman product design",
      "Mahir Figma",
      "Portfolio yang kuat",
      "Pengalaman dengan design systems",
    ],
    benefits: [
      "Asuransi kesehatan",
      "Stock options",
      "Jam kerja fleksibel",
      "Budget konferensi design",
    ],
    category: "Design",
    experience: "mid",
    postedAt: "2025-01-24",
    featured: true,
    tags: ["Figma", "UI/UX", "Design Systems", "Prototyping"],
  },
  {
    id: "3",
    companyId: "4",
    title: "DevOps Engineer",
    company: "Bukalapak",
    companyLogo: "/bukalapak-logo-red.jpg",
    location: "Remote",
    type: "remote",
    salary: { min: 20000000, max: 35000000, currency: "IDR" },
    description:
      "Bantu kami menskalakan infrastruktur untuk mendukung jutaan transaksi per hari.",
    requirements: [
      "Pengalaman AWS/GCP",
      "Kubernetes",
      "Terraform",
      "CI/CD pipelines",
    ],
    benefits: [
      "100% remote",
      "Budget peralatan",
      "Asuransi kesehatan",
      "Annual retreat",
    ],
    category: "Engineering",
    experience: "senior",
    postedAt: "2025-01-23",
    tags: ["AWS", "Kubernetes", "Docker", "Terraform"],
  },
  {
    id: "4",
    companyId: "6",
    title: "Marketing Manager",
    company: "Shopee Indonesia",
    companyLogo: "/shopee-logo-orange.jpg",
    location: "Jakarta Pusat",
    type: "full-time",
    salary: { min: 15000000, max: 25000000, currency: "IDR" },
    description:
      "Pimpin inisiatif marketing dan dorong pertumbuhan di semua channel.",
    requirements: [
      "5+ tahun pengalaman marketing",
      "Background e-commerce",
      "Pendekatan berbasis data",
      "Kepemimpinan tim",
    ],
    benefits: [
      "Gaji kompetitif",
      "Bonus performa",
      "Asuransi kesehatan",
      "Kerja fleksibel",
    ],
    category: "Marketing",
    experience: "senior",
    postedAt: "2025-01-22",
    tags: ["E-commerce", "Digital Marketing", "Growth", "Analytics"],
  },
  {
    id: "5",
    companyId: "3",
    title: "Junior Software Developer",
    company: "Traveloka",
    companyLogo: "/traveloka-logo-blue.jpg",
    location: "Jakarta Selatan",
    type: "full-time",
    salary: { min: 8000000, max: 12000000, currency: "IDR" },
    description:
      "Kesempatan bagus untuk fresh graduate untuk berkembang bersama startup unicorn.",
    requirements: [
      "Lulusan S1 IT/CS",
      "Pengetahuan JavaScript",
      "Semangat belajar",
      "Team player",
    ],
    benefits: [
      "Program mentorship",
      "Stock options",
      "Budget pembelajaran",
      "Asuransi kesehatan",
    ],
    category: "Engineering",
    experience: "entry",
    postedAt: "2025-01-21",
    tags: ["JavaScript", "React", "Node.js", "Fresh Graduate"],
  },
  {
    id: "6",
    companyId: "6",
    title: "Sales Representative",
    company: "Mekari",
    companyLogo: "/mekari-logo-purple.jpg",
    location: "Tangerang Selatan",
    type: "full-time",
    salary: { min: 7000000, max: 15000000, currency: "IDR" },
    description:
      "Bergabung dengan tim sales untuk membantu bisnis Indonesia bertransformasi digital.",
    requirements: [
      "2+ tahun B2B sales",
      "Pengalaman CRM",
      "Komunikasi yang baik",
      "Self-motivated",
    ],
    benefits: [
      "Gaji pokok + komisi",
      "Asuransi kesehatan",
      "Tunjangan transportasi",
      "Bonus tahunan",
    ],
    category: "Sales",
    experience: "mid",
    postedAt: "2025-01-20",
    tags: ["B2B", "SaaS", "Enterprise", "Sales"],
  },
  {
    id: "7",
    companyId: "7",
    title: "Data Scientist",
    company: "OVO",
    companyLogo: "/ovo-logo-purple-fintech.jpg",
    location: "Jakarta Selatan",
    type: "full-time",
    salary: { min: 22000000, max: 40000000, currency: "IDR" },
    description:
      "Bekerja dengan model ML mutakhir untuk fintech terbesar di Indonesia.",
    requirements: [
      "S2/S3 bidang relevan",
      "Mahir Python/R",
      "ML frameworks",
      "Background riset",
    ],
    benefits: [
      "Budget riset",
      "Konferensi internasional",
      "Stock options",
      "Jam fleksibel",
    ],
    category: "Engineering",
    experience: "senior",
    postedAt: "2025-01-19",
    featured: true,
    tags: ["Machine Learning", "Python", "TensorFlow", "Data Science"],
  },
  {
    id: "8",
    companyId: "8",
    title: "UX Researcher",
    company: "Blibli",
    companyLogo: "/blibli-logo-blue-ecommerce.jpg",
    location: "Jakarta Barat",
    type: "contract",
    salary: { min: 12000000, max: 18000000, currency: "IDR" },
    description:
      "Bantu kami memahami pengguna dan tingkatkan produk melalui riset.",
    requirements: [
      "3+ tahun UX research",
      "Pengalaman mixed methods",
      "Kemampuan analitis kuat",
      "Presentasi yang baik",
    ],
    benefits: ["Jadwal fleksibel", "Opsi remote", "Budget tools riset"],
    category: "Design",
    experience: "mid",
    postedAt: "2025-01-18",
    tags: ["UX Research", "User Testing", "Analytics", "Design"],
  },
  {
    id: "9",
    companyId: "9",
    title: "Backend Engineer",
    company: "Dana Indonesia",
    companyLogo: "/dana-logo-blue-fintech.jpg",
    location: "Jakarta Pusat",
    type: "full-time",
    salary: { min: 18000000, max: 32000000, currency: "IDR" },
    description:
      "Bangun sistem pembayaran yang aman dan scalable untuk jutaan pengguna.",
    requirements: [
      "4+ tahun backend development",
      "Go/Java",
      "Microservices",
      "Database optimization",
    ],
    benefits: ["Gaji kompetitif", "Asuransi lengkap", "WFH 2x seminggu", "THR"],
    category: "Engineering",
    experience: "mid",
    postedAt: "2025-01-17",
    tags: ["Go", "Java", "Microservices", "PostgreSQL"],
  },
  {
    id: "10",
    companyId: "10",
    title: "Content Writer",
    company: "Kompas.com",
    companyLogo: "/kompas-logo-news-media.jpg",
    location: "Jakarta Pusat",
    type: "full-time",
    salary: { min: 6000000, max: 10000000, currency: "IDR" },
    description:
      "Tulis artikel berkualitas untuk portal berita terbesar di Indonesia.",
    requirements: [
      "Lulusan jurnalistik/komunikasi",
      "Kemampuan menulis excellent",
      "SEO knowledge",
      "Deadline-oriented",
    ],
    benefits: [
      "Asuransi kesehatan",
      "Tunjangan makan",
      "Cuti tahunan",
      "Training berkala",
    ],
    category: "Marketing",
    experience: "entry",
    postedAt: "2025-01-16",
    tags: ["Content Writing", "SEO", "Journalism", "Digital Media"],
  },
];

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "Tokopedia",
    logo: "/tokopedia-logo-green.jpg",
    description:
      "Platform e-commerce terbesar di Indonesia yang menghubungkan jutaan penjual dan pembeli.",
    website: "https://tokopedia.com",
    location: "Jakarta Selatan",
    size: "5000+",
    industry: "E-commerce",
    founded: 2009,
    jobs: [],
  },
  {
    id: "2",
    name: "Gojek",
    logo: "/gojek-logo-green.jpg",
    description:
      "Super app Indonesia untuk transportasi, pembayaran, dan layanan on-demand.",
    website: "https://gojek.com",
    location: "Jakarta Selatan",
    size: "5000+",
    industry: "Technology",
    founded: 2010,
    jobs: [],
  },
  {
    id: "3",
    name: "Traveloka",
    logo: "/traveloka-logo-blue.jpg",
    description: "Platform travel dan lifestyle terkemuka di Asia Tenggara.",
    website: "https://traveloka.com",
    location: "Jakarta Selatan",
    size: "1000-5000",
    industry: "Travel Tech",
    founded: 2012,
    jobs: [],
  },
  {
    id: "4",
    name: "Bukalapak",
    logo: "/bukalapak-logo-red.jpg",
    description:
      "E-commerce dan mitra warung yang memberdayakan UMKM Indonesia.",
    website: "https://bukalapak.com",
    location: "Jakarta Selatan",
    size: "1000-5000",
    industry: "E-commerce",
    founded: 2010,
    jobs: [],
  },
  {
    id: "5",
    name: "OVO",
    logo: "/ovo-logo-purple-fintech.jpg",
    description:
      "Platform pembayaran digital dan layanan keuangan terkemuka di Indonesia.",
    website: "https://ovo.id",
    location: "Jakarta Selatan",
    size: "1000-5000",
    industry: "Fintech",
    founded: 2017,
    jobs: [],
  },
  {
    id: "6",
    name: "Shopee Indonesia",
    logo: "/shopee-logo-orange.jpg",
    description: "Platform e-commerce mobile-first yang populer di Indonesia.",
    website: "https://shopee.co.id",
    location: "Jakarta Pusat",
    size: "5000+",
    industry: "E-commerce",
    founded: 2015,
    jobs: [],
  },
];

// Initialize company jobs
mockCompanies.forEach((company) => {
  company.jobs = mockJobs.filter((j) => j.company === company.name);
});
